name: Main workflow

on: push

jobs:
#  eslint:
#    name: ESLint
#    runs-on: ubuntu-latest
#    steps:
#       - name: Checkout code  
#         uses: actions/checkout@v3
#       - name: Install modules
#         run: yarn
#       - name: Run ESLint
#         run: yarn lint

 build:
   name: Build
   runs-on: ubuntu-latest
   #needs:  eslint
   steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      run: |
        yarn install
        yarn build
    - name: Upload artifacts in order to deploy
      uses: actions/upload-artifact@v2
      with: 
        name: productions-files
        path: ./build
      

#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#       - uses: actions/checkout@v2
#       - name: Install modules
#         run : yarn install
#       - name: Run tests
#         run: yarn test

 deploy:
   name: Deploy
   runs-on: ubuntu-latest
   needs: build
   steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: productions-files
          path: ./build
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./build